# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  config.disksize.size = '100GB'

  config.vm.box_check_update = false
  config.ssh.insert_key = false  
  
  # change memory size
  config.vm.provider "virtualbox" do |v|
    v.memory = 8129
    v.name = 'CentOS7_OpenStack'
    v.cpus = 8
  end

#  config.vm.network "private_network", ip: "192.168.88.88"
  config.vm.network "forwarded_port", guest: 443, host: 443
  config.vm.provision "shell", path: "scripts/install.sh"
end