# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    v.name = 'awx'
  end

  config.vm.synced_folder ".", "/vagrant"
  config.vm.define "nextcloud", primary: true do |server|
    server.vm.hostname = "nextcloud"
    server.vm.network "private_network", ip: "192.168.4.2"
    server.vm.provision "shell", path: "scripts/install.sh"
  end

end
