# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.define "pgnode02" do |server|
    server.vm.hostname = "pgnode02"
    server.vm.network "private_network", ip: "192.168.4.3"
    server.vm.provision "shell", path: "scripts/slave.sh"
  end

  config.vm.define "pgnode03" do |server|
    server.vm.hostname = "pgnode03"
    server.vm.network "private_network", ip: "192.168.4.4"
    server.vm.provision "shell", path: "scripts/slave.sh"
  end

  config.vm.define "pgnode04" do |server|
    server.vm.hostname = "pgnode04"
    server.vm.network "private_network", ip: "192.168.4.5"
    server.vm.provision "shell", path: "scripts/slave.sh"
  end
  config.vm.define "pgnode05" do |server|
    server.vm.hostname = "pgnode05"
    server.vm.network "private_network", ip: "192.168.4.6"
    server.vm.provision "shell", path: "scripts/slave.sh"
  end
  config.vm.define "pgnode01", primary: true do |server|
    server.vm.hostname = "pgnode01"
    server.vm.network "private_network", ip: "192.168.4.2"
    server.vm.network "forwarded_port", guest: 5432, host: 5432
    server.vm.network "forwarded_port", guest: 6432, host: 6432
    server.vm.provision "shell", path: "scripts/master.sh"
  end

end
