# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "generic/rocky8"

  config.vm.define "es2" do |server|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
#    v.gui = true
    v.cpus = 2
  end

    server.vm.network "private_network", ip: "192.168.4.3"
   server.vm.provision "shell", path: "scripts/slave.sh"
  end

  config.vm.define "es3" do |server|
    server.vm.hostname = "es3"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
#    v.gui = true
    v.cpus = 2
  end

    server.vm.network "private_network", ip: "192.168.4.4"
    server.vm.provision "shell", path: "scripts/slave.sh"
  end

  config.vm.define "es1", primary: true do |server|
    server.vm.hostname = "es1"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
#    v.gui = true
    v.cpus = 2
  end

    server.vm.network "private_network", ip: "192.168.4.2"
    server.vm.provision "shell", path: "scripts/master.sh"
  end

end

