# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

PG_DATABASE_NAME = "pgdb1"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"

  config.vm.define "slave1" do |server|
    server.vm.hostname = "slave1.pg"
    server.vm.network "private_network", ip: "192.168.4.3"
    server.vm.network "forwarded_port", guest: 5432, host: 5433
    server.vm.provision "shell", path: "scripts/slave.sh"
  end

  config.vm.define "slave2" do |server|
    server.vm.hostname = "slave2.pg"
    server.vm.network "private_network", ip: "192.168.4.4"
    server.vm.network "forwarded_port", guest: 5432, host: 5434
    server.vm.provision "shell", path: "scripts/slave.sh"
  end

  config.vm.define "slave3" do |server|
    server.vm.hostname = "slave3.pg"
    server.vm.network "private_network", ip: "192.168.4.5"
    server.vm.network "forwarded_port", guest: 5432, host: 5435
    server.vm.provision "shell", path: "scripts/slave.sh"
  end

  config.vm.define "slave4" do |server|
    server.vm.hostname = "slave4.pg"
    server.vm.network "private_network", ip: "192.168.4.6"
    server.vm.network "forwarded_port", guest: 5432, host: 5436
    server.vm.provision "shell", path: "scripts/slave.sh"
  end
  config.vm.define "slave5" do |server|
    server.vm.hostname = "slave5.pg"
    server.vm.network "private_network", ip: "192.168.4.7"
    server.vm.network "forwarded_port", guest: 5432, host: 5437
    server.vm.provision "shell", path: "scripts/slave.sh"
  end
  config.vm.define "slave6" do |server|
    server.vm.hostname = "slave6.pg"
    server.vm.network "private_network", ip: "192.168.4.8"
    server.vm.network "forwarded_port", guest: 5432, host: 5438
    server.vm.provision "shell", path: "scripts/slave.sh"
  end


  config.vm.define "master", primary: true do |server|
    server.vm.hostname = "master.pg"
    server.vm.network "private_network", ip: "192.168.4.2"
    server.vm.network "forwarded_port", guest: 5432, host: 5432
    server.vm.provision "shell", path: "scripts/master.sh"
  end

end
