# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  
  config.vm.box_check_update = false
  
  # change memory size
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.name = 'CentOS7_pg10.5'
  end

  config.vm.network "forwarded_port", guest: 5432, host: 5432
  config.vm.provision "shell", path: "scripts/install.sh"
end