#
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  
  # change memory size
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.cpus = 2
    vb.name = "CentOS7-nfs-vagrant"
  end

  # NFS port forwarding
  config.vm.network "forwarded_port", guest: 2049, host: 2049, protocol: "udp"
  config.vm.network "forwarded_port", guest: 2049, host: 2049, protocol: "tcp"

  config.ssh.insert_key = false  

  # Provision everything on the first run
  config.vm.provision "shell", path: "install_nfs.sh"
end
