# vagrant / zabbix 4.0 / virtualbox
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-8"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.provision "shell", inline: <<-SHELL
    wget https://repo.zabbix.com/zabbix/4.4/rhel/8/x86_64/zabbix-release-4.4-1.el8.noarch.rpm
    yum localinstall zabbix-release-4.4-1.el8.noarch.rpm -y
    yum update
    systemctl disable firewalld
    systemctl stop firewalld
    sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
    setenforce 0
    yum install mc mysql-server -y
    yum install zabbix-server-mysql zabbix-web-mysql zabbix-apache-conf -y
    sed -i "s|; ||g" /etc/php-fpm.d/zabbix.conf
    sed -i "s|Europe/Riga|Europe/Moscow|g" /etc/php-fpm.d/zabbix.conf
    echo -e "[mysqld]\ndefault-storage-engine = innodb" | sudo tee /etc/my.cnf.d/mysql-server.cnf
    service mysqld restart
    mysql -e "CREATE USER 'zabbix'@'%' IDENTIFIED BY 'zabbix';"
    mysql -e "create database zabbix character set utf8 collate utf8_bin;"
    mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'zabbix'@'%';"
    zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz | mysql -uzabbix -p"zabbix" zabbix
    sed 's/# DBPassword=/DBPassword=zabbix/g' /etc/zabbix/zabbix_server.conf -i
    service zabbix-server restart
    service httpd restart
    service php-fpm restart
    yum install zabbix-agent -y
    mkdir /var/lib/zabbix -p
    cat > /var/lib/zabbix/.my.cnf <<EOF
[client]
user = zabbix
password = zabbix
host = localhost
EOF
    chown zabbix:zabbix -R /var/lib/zabbix
cat > /etc/sysconfig/zabbix-agent  <<EOF
HOME=/var/lib/zabbix
export HOME
EOF
    service zabbix-agent restart

    echo "Zabbix frontend is ready!"
    echo "open http://localhost:8080/zabbix"
    echo "The default user name is 'Admin', password 'zabbix'."
  SHELL
end