---
galaxy_info:
  author: rbicker
  description: install or upgrade nextcloud
  license: MIT
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - nextcloud
dependencies: []
