es_config: {
   node.name: "es1",  
#   node.data: true,
#   node.master: true,
#   node.ingest: false,
#8.0
   node.roles: [ data, master, ingest ],
   network.host: "192.168.4.2,127.0.0.1", 
#   network.bind_host: 192.168.4.2,
   cluster.name: "es-cluster", 
   cluster.initial_master_nodes: "192.168.4.2:9300", 
   discovery.seed_hosts: "192.168.4.2:9300,192.168.4.3:9300,192.168.4.4:9300", 
   http.port: 9200,
   transport.port: 9300,
   bootstrap.memory_lock: false,
#8.0
   xpack.security.transport.ssl.enabled: false,
   xpack.security.http.ssl.enabled: false,
   xpack.security.enabled: false,
   }
