# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"

  config.vm.define "my2" do |server|
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

    server.vm.network "private_network", ip: "192.168.4.3"
    server.vm.network "forwarded_port", guest: 3306, host: 37017
   server.vm.provision "shell", path: "scripts/slave.sh"
  end

  config.vm.define "my3" do |server|
    server.vm.hostname = "my3"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

    server.vm.network "private_network", ip: "192.168.4.4"
    server.vm.network "forwarded_port", guest: 3306, host: 47017
    server.vm.provision "shell", path: "scripts/slave.sh"
  end

  config.vm.define "my1", primary: true do |server|
    server.vm.hostname = "my1"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

    server.vm.network "private_network", ip: "192.168.4.2"
    server.vm.network "forwarded_port", guest: 3306, host: 3306
    server.vm.provision "shell", path: "scripts/master.sh"
  end

end
