#
# LICENSE UPL 1.0
#
# Copyright (c) 1982-2018 Oracle and/or its affiliates. All rights reserved.
# 
# Since: July, 2018
# Author: gerald.venzl@oracle.com
# Description: Creates an Oracle database Vagrant virtual machine.
# 
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
# 

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ksa/centos7_cifs"
  
  # change memory size
#  config.vm.synced_folder ".", "/vagrant", type:"smb", smb_host:"192.168.137.1", smb_username: "username", smb_password: "*******", mount_options: ["vers=3.0"]
  config.vm.synced_folder ".", "/vagrant", type:"smb", smb_host:"192.168.137.1", mount_options: ["vers=3.0"]

  config.vm.provider "hyperv" do |v|
    v.memory = 2048
    v.vmname = "CentOS7-oracle-11g"
  end

  # Oracle port forwarding
  config.vm.network "forwarded_port", guest: 1521, host: 1521
  config.vm.network "forwarded_port", guest: 5500, host: 5500

  config.ssh.insert_key = false  

  # Provision everything on the first run
  config.vm.provision "shell", path: "scripts/install.sh", env:
    {
       "ORACLE_BASE"         => "/opt/oracle",
       "ORACLE_HOME"         => "/opt/oracle/product/11.2.0.4/dbhome_1",
       "ORACLE_SID"          => "ORCL",
       "ORACLE_CHARACTERSET" => "AL32UTF8",
       "ORACLE_EDITION"      => "EE"
    }


end
