---
# handlers file for rbicker.nextcloud

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: reload php-fpm
  service:
    name: php-fpm
    state: reloaded

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted

- name: restart mariadb
  service:
    name: mariadb
    state: restarted

- name: restart redis
  service:
    name: redis
    state: restarted

- name: mysql optimization
  lineinfile:
    path: /etc/my.cnf.d/server.cnf
    regexp: '^{{ item.option }}'
    line: '{{ item.option }}={{ item.value }}'
    insertafter: '\[mysqld\]'
  with_items:
    - { option: ignore-db-dir, value: lost+found }
    - { option: innodb_file_per_table, value: 1 }
    - { option: default-storage-engine, value: InnoDB }
    - { option: innodb_large_prefix, value: "true" }
    - { option: innodb_file_format, value: barracuda }
    - { option: innodb_buffer_pool_size, value: 4G }
    - { option: innodb_log_file_size, value: 2G }
    - { option: character-set-server, value: utf8mb4 }
    - { option: bind-address, value: 127.0.0.1 }

- name: add missing indices
  command: '{{ nextcloud_web_root }}/occ db:add-missing-indices'
  become: yes
  become_user: nginx
  changed_when: no

- name: convert columns to big int
  command: '{{ nextcloud_web_root }}/occ db:convert-filecache-bigint --no-interaction'
  become: yes
  become_user: nginx
  changed_when: no

- name: add mimetypes to database
  command: '{{ nextcloud_web_root }}/occ maintenance:mimetype:update-db'
  become: yes
  become_user: nginx
  changed_when: no
