# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
#  config.vm.box = "bento/centos-8"
#  config.vm.box = "generic/rhel7"
  config.vm.box = "centos/7"
  
  config.vm.box_check_update = false
  config.ssh.insert_key = false  
  
  # change memory size
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.name = 'CentOS7_MySQL_ansible_55'
  end

  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.provision "shell", path: "scripts/install.sh"
end