# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1812.01"  
  config.vm.box_check_update = false
  
  # change memory size
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.name = 'MSSQL2017_Linux'
  end

  config.vm.network "forwarded_port", guest: 1433, host: 1433
  config.vm.provision "shell", path: "scripts/install.sh"
end