- hosts: all
  become: yes
  pre_tasks:
   - name: Enabling epel repository
     yum:
       name:
          - epel-release
       state: latest
     tags: software

   - name: Install packages
     yum:
       state: latest
       name:
          - zip
          - unzip
          - atop
          - wget
          - mytop
          - htop
          - mc
          - telnet
          - net-tools
     tags: software
   - name: Add IP address of all hosts to all hosts
     lineinfile:
          dest: /etc/hosts
          regexp: '.*{{ item }}$'
          line: "{{ hostvars[item].ansible_host }} {{item}}"
          state: present
     when: hostvars[item].ansible_host is defined
     with_items: "{{ groups.all }}"
     tags: etc_hosts

  roles:
    - role: postgresql

